name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        uses: huggingface/hub-action@v1
        with:
          repo: spaces/hutchingd/Cassidy-Bot
          repo-token: ${{ secrets.HF_TOKEN }}
        
